### ISSUE TITLE
Box Theme

### ISSUE THREAD

**Issue by tenplus1** [Extrawurst/DerelictLibui#6]
Rather than provide images to make up a theme for this lovely GUI, how about a simple and fast drawn theme using nothing but box theme files to control colour, line style, gradients and padding...  It should draw a lot quicker than image themes, be a lot smaller and there are MANY box themes available to provide almost any look you could want: https://www.box-look.org/browse/ord/latest/

**Comment by ghost** [comment]
Wrong place I guess ?
1.  it's a binding, design decisions are not made here.
2.  this kind of GUIs use the OS specific GUI engines which do bitmap blitting from theme elements, thus theming is only possible by tweaking either Windows (UXTheme patcher) or Gtk (dedicated tool maybe)
